name: Bug report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    attributes:
      label: Browsers
      description: What browsers are you seeing the problem on?
      placeholder: Firefox, Chrome, etc...
    validations:
      required: false
  - type: input
    attributes:
      label: Operating system
      description: What operating system are you seeing the problem on?
      placeholder: Windows, Linux, etc...
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Priority level
      description: The level of priority the bug fix should have
      multiple: false
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: input
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/vtexdocs/helpcenter/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true